# Custom workspace and checkout locations
workspaceLocation: gitpod/gitpod.code-workspace  # Refers to .code-workspace file
checkoutLocation: /workspace/hello-nextflow # Ensure Git clones into the correct location

# GitHub prebuild configuration
github:
  prebuilds:
    # Enable prebuilds for the master/default branch
    master: true
    # Disable prebuilds for all branches
    branches: false
    # Enable prebuilds for pull requests from this repo
    pullRequests: true
    # Enable prebuilds for pull requests from forks
    pullRequestsFromForks: true
    # Disable "Review in Gitpod" comment on PRs
    addComment: false
    # Disable "Review in Gitpod" badge on PRs
    addBadge: false

# Docker image to use for the workspace
image:
  file: .github/.gitpod.Dockerfile


# Tasks to execute during workspace initialisation and startup
tasks:
  - before: printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc && exit

  # Create directory structure 
  - name: Create Directories
    init: |
      mkdir -p /workspace/hello-nextflow/part1
      mkdir -p /workspace/hello-nextflow/part2

# Download containers to be used in part 2 
  - name: Download containers
    init: |
      docker pull quay.io/biocontainers/salmon:1.10.1--h7e5ed60_0
      docker pull quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0
      docker pull quay.io/biocontainers/multiqc:1.19--pyhdfd78af_0
    command: docker run hello-world

# Open docs in a web browser
  - name: Open Documentation Page
    command: gp ports await 23000 && gp preview https://sydney-informatics-hub.github.io/hello-nextflow/

# Start the tutorial 
  - name: Start tutorial
    command: |
      cd hello-nextflow
      source $HOME/.bashrc
      export PS1='\[\e[3;36m\]${PWD/*\//} ->\[\e[0m\] '
      unset JAVA_TOOL_OPTIONS
      clear

# VSCode extensions to install in the workspace
vscode:
  extensions:
    - codezombiech.gitignore           # Support for .gitignore files
    - cssho.vscode-svgviewer           # SVG viewer
    - esbenp.prettier-vscode           # Prettier for markdown formatting
    #- EditorConfig.EditorConfig       # Support for .editorconfig
    #- Gruntfuggly.todo-tree           # Display TODO/FIXME comments in a tree view
    - nextflow.nextflow                # Nextflow syntax highlighting
    - streetsidesoftware.code-spell-checker # Spell checker for source code
    - ms-vscode.live-server            # Live server for web development
